# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz.xci
# IP: The module: 'clk_wiz_12MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_12MHz'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz.xci
# IP: The module: 'clk_wiz_12MHz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/clk_wiz_12MHz/clk_wiz_12MHz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_12MHz'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
