# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/divisor/divisor.xci
# IP: The module: 'divisor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/divisor/divisor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divisor'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/divisor/divisor.xci
# IP: The module: 'divisor' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zyj/magic code/project_1/project_1.srcs/sources_1/ip/divisor/divisor_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divisor'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
